apiVersion: v1
kind: Secret
metadata:
  name: xapisecrets
type: Opaque
stringData:
  NotificationEmailAddress: $NotificationEmailAddress
  NotificationPassword: $NotificationPassword

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-info
  template:
    metadata:
      labels:
        app: covid-info
    spec:
      containers:
      - image: inftfg2021/covid-info:$TAG
        name: covid-info
        env:
          - name: API_HOST
            valueFrom:
              secretKeyRef:
                name: xapisecrets
                key: CovidInfoAPIHost
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: xapisecrets
                key: CovidInfoAPIKey
---
apiVersion: v1
kind: Service
metadata:
  name: covid-info
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "covid-info"
    port: 5000
  selector:
    app: covid-info
